### ISSUE TITLE
Don't choose thread by name

### ISSUE THREAD

**Issue by KineticFox** [KineticFox/loa-lfgBot#20]
If you want to join a group and there is a group with the same name strange behavior happesn because of two groups with the same name.

**Comment by BaluderTanzbaer** [comment]
Replace

```
allThreads = chanell.threads


          for t in allThreads:
                 if t.name == embed.title:
                     thread_id = t.id

          thread = chanell.get_thread(thread_id)
```


With
`thread = chanell.get_thread(interaction.message.id)`

**Comment by BaluderTanzbaer** [comment]
Since threads are based in messages they Share the same ID (at least here since you create the thread in top of your raid-embed-message

**Comment by KineticFox** [comment]
Yes this works, thanks.
