### ISSUE TITLE
@role in raid message

### ISSUE THREAD

**Issue by Reekfrin** [KineticFox/loa-lfgBot#40]
Ping specific roles (Valtan,Vykas,Kakul-Saydon,Brelshaza,Akkan,Kayangel etc.) in "A wild raid spawns"-message.

not sure if you can just get "fname" and put it into chanell.send command with an @ before.

**Comment by KineticFox** [comment]
Not sure when to implement it, because those roles aren't there yet.

**Comment by KineticFox** [comment]
Done
